version: '3.7'
volumes:
  redis-data:
    driver: local
services:
  # app:
  #   container_name: tkj-league-ng
  #   build: app/.
  #   environment: 
  #     - APP_ENV=dev
  #   ports:
  #     - 4200:4200
  api:
    container_name: tkj-league-e4
    build: api/.
    environment: 
      - APP_ENV=localhost
    ports:
      - 3000:3000
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
